#!/bin/sh -e

cleanup()
{
    rm -rf "$DEST/usr/share/bash-completion" \
           "$DEST/usr/share/applications" \
           "$DEST/etc/bash_completion.d" \
           "$DEST/usr/lib/charset.alias" \
           "$DEST/usr/share/polkit-1" \
           "$DEST/usr/share/gettext" \
           "$DEST/usr/share/gtk-doc" \
           "$DEST/usr/share/locale" \
           "$DEST/usr/share/sounds" \
           "$DEST/usr/share/icons" \
           "$DEST/usr/share/info" \
           "$DEST/usr/share/doc" \
           "$DEST/usr/share/man" \
           "$DEST/usr/share/zsh"
}

# int main()
{
    case $TYPE in
        pre-extract)
            case $PKG in
                firefox|firefox-esr|rust|llvm|clang|gcc)
                    mak_dir=$KISS_TMPDIR/build-$pid
                    pkg_dir=$KISS_TMPDIR/pkg-$pid
                ;;

                *)
                    log "$PKG" "Activating tmpfs"

                    mak_dir=/tmp/build-$pid
                    pkg_dir=/tmp/pkg-$pid
                ;;
            esac

            mkdir -p "$mak_dir" "$pkg_dir/$PKG/var/db/kiss/installed"
        ;;

        pre-build)
            IFS=. read -r _start _ < /proc/uptime

            case $PKG in
                baselayout)
                    sed -i 's/home //g'                  "$repo_dir/build"
                    sed -i 's/bin i/bin home i/g'        "$repo_dir/build"
                    sed -i '30iln -s usr/home "$1/home"' "$repo_dir/build"
                ;;

                busybox)
                    sed -i "s|\.profile|etc/profile|g" shell/ash.c
                    sed -i "s|/home|/usr/home|g"       loginutils/adduser.c
                ;;

                mesa)
                    _flags=-Dgallium-drivers=radeonsi
                    _flags=$_flags\ -Dvulkan-drivers=amd
                    _flags=$_flags\ -Dgallium-va=enabled

                    sed -i "s/\. output/$_flags \0/" "$repo_dir/build"
                ;;

                scroll)
                    sed -i "s|//||g" config.def.h
                ;;
            esac
        ;;

        post-build)
            IFS=. read -r _end _ < /proc/uptime

            (
                _s=$((_end - _start))
                _h=$((_s / 60 / 60 % 24))
                _m=$((_s / 60 % 60))

                [ "$_h" = 0 ] || _u="${_u}${_h}h "
                [ "$_m" = 0 ] || _u="${_u}${_m}m "

                log "$PKG" "Build finished in ${_u:-${_s}s}"
            )

            : "${DEST:?DEST is unset}"

            case $PKG in
                abiword)
                ;;

                adwaita-icon-theme)
                ;;

                alsa-lib)
                    _files="~/etc/asound.conf"

                    sed -i "s@~/.asoundrc@$_files|||\0@" "$DEST/usr/share/alsa/alsa.conf"

                    cleanup
                ;;

                baselayout)
                    sed -i 's/home i/i/g'         "$repo_dir/build"
                    sed -i 's/etc m/etc home m/g' "$repo_dir/build"
                    sed -i '/usr\/home/d'         "$repo_dir/build"
                ;;

                busybox)
                    {
                        echo "kvm         root:kvm 660"
                        echo "SUBSYSTEM=drm;.*   root:video 660 *env > /tmp/.libudev-zero/uevent.\$$"
                        echo "SUBSYSTEM=input;.* root:input 660 *env > /tmp/.libudev-zero/uevent.\$$"
                    } >> "$DEST/etc/mdev.conf"
                ;;

                gnumeric)
                ;;

                goffice)
                ;;

                kiss)
                    sed -i "s/grub/metapkg/g" "$DEST/usr/bin/kiss-orphans"
                ;;

                libudev-zero)
                    cc contrib/helper.c -o helper
                    install -Dm755 helper "$DEST/usr/bin/helper"

                    cleanup
                ;;

                mesa)
                    _flags=-Dgallium-drivers=radeonsi
                    _flags=$_flags\ -Dvulkan-drivers=amd
                    _flags=$_flags\ -Dgallium-va=enabled

                    sed -i "s/$_flags //" "$repo_dir/build"

                    cleanup
                ;;

                *)
                    cleanup
                ;;
            esac
        ;;

        pre-install)
            case $PKG in
                linux)
                    mount /dev/sdb2 /boot
                ;;
            esac
        ;;
                

        post-install)
            case $PKG in
                linux)
                    umount /boot
                ;;

                sls)
                    chown root:eudaldgr /usr/bin/sls
                    chmod gu+s          /usr/bin/sls
                ;;
            esac
         ;;
    esac
}
