#!/bin/sh -e

case "$1" in
    alternatives|build|checksum|download|install|list|remove|search|update|version|'')
        /usr/bin/kiss "$@"
    ;;
    ro)
        while kiss o | grep -qv "${2:-metapkg}"; do
            kiss r `kiss o | grep -v "${2:-metapkg}" | tr '\n' ' '`
        done
    ;;
    *)
        _1="$1"
        shift 1
        for _opt in $(echo "$_1" | grep -o .); do
            /usr/bin/kiss "$_opt" "$@"
        done
    ;;
esac
