#!/bin/sh -e

case "$1" in
    bi)
        kiss b  "${2:-}" && kiss i  "${2:-}"
    ;;

    cb)
        kiss c  "${2:-}" && kiss b  "${2:-}"
    ;;

    cbi)
        kiss cb "${2:-}" && kiss i  "${2:-}"
    ;;

    ro)
        while kiss o | grep -qv "${2:-metapkg}"; do
            kiss r `kiss o | grep -v "${2:-metapkg}" | tr '\n' ' '`
        done
    ;;

    *)
        /usr/bin/kiss "$@"
    ;;
esac
