#!/bin/sh

[ "$1" ] || exit 1

pkg="$HOME/usr/skel/pkg"

kiss n "$2" "$3" "$4"

case "$1" in
    autotool|a) cp "$pkg/autotools" "$2/build" ;;
    cmake|c)    cp "$pkg/cmake"     "$2/build" ;;
    go|g)       cp "$pkg/go"        "$2/build" ;;
    make|mk)    cp "$pkg/make"      "$2/build" ;;
    meson|m)    cp "$pkg/meson"     "$2/build" ;;
    python|p)   cp "$pkg/python"    "$2/build" ;;
    rust|r)     cp "$pkg/rust"      "$2/build" ;;
esac

chmod +x "$2/build"
