#!/bin/sh

[ "$1" ] || exit 1

case "$1" in
    --script|-s)
        [ -e "$HOME/bin/$2" ] || {
            printf '#!/bin/sh\n' > "$HOME/bin/$2" && chmod +x "$HOME/bin/$2"
            nvim "$HOME/bin/$2"
        }
    ;;
esac
