#!/bin/sh

[ -f "$HOME/usr/virt/${0##*/}/hdd.img" ] || {
    mkdir -p "$HOME/usr/virt/${0##*/}"
    qemu-img create -f qcow2 "$HOME/usr/virt/${0##*/}/hdd.img" 16G
}

qemu-system-x86_64 \
    -enable-kvm \
    -cpu host \
    -smp 4 \
    -m 4G \
    -drive file="$HOME/usr/virt/${0##*/}/hdd.img",if=virtio \
    -nic user,hostfwd=tcp::10022-:22,model=virtio-net-pci \
    -vga virtio \
    -display sdl,gl=on \
    -boot menu=on \
    -usb \
    "$@"
