#!/bin/sh -e
#
# open file in application based on file extension

case $1 in
    *.mp3|*.flac|*.wav)
        mpv --no-video "$1"
    ;;

    *.mp4|*.mkv|*.webm)
        mpv "$1"
    ;;

    *.png|*.gif|*.jpg|*.jpe|*.jpeg)
        sxiv "$1"
    ;;

    *.html|*.pdf)
        firefox "$1"
    ;;

    *.torrent)
        rtorrent "$1"
    ;;

    *)
        "${EDITOR:=vi}" "$1"
    ;;
esac
