#!/bin/sh -e
#
# open file in application based on file extension

case $1 in
    *.mp3|*.flac|*.wav)
        mpv --no-video "$1"
    ;;

    *.mp4|*.mkv|*.webm)
        mpv "$1"
    ;;

    *.png|*.gif|*.jpg|*.jpe|*.jpeg)
        sxiv "$1"
    ;;

    *.html|*.pdf)
        $HOME/usr/bin/ff "$1"
    ;;

    *.torrent)
        rtorrent -n -o import=$HOME/etc/rtorrent.rc "$1"
    ;;

    *.doc|*.docx)
        abiword "$1"
    ;;

    *)
        "${EDITOR:=vi}" "$1"
    ;;
esac
